name: simple workflow
on:
   push:
     branches:
        - master
jobs:
    Deploment:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4
        

